# application.yml
spring:
  application:
    name: Study Rooms

  datasource:
    url: jdbc:postgresql://dpg-d5bro7je5dus73fujq1g-a.frankfurt-postgres.render.com:5432/studyroomsdb_8jgd
    username: studyroomsusr
    password: dKOm22tAwQ2TB8ap9mXnkrmcqod27aPL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true

server:
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-exception: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Custom Application Properties.
app:
  jwt:
    issuer: "office-hours-api"
    audience: "external-systems"
    secret: "${JWT_SECRET:CZdgSym1G85S2lG3LFd3dufas53SakV3kXEqxTgy1vY=}" # openssl rand -base64 32
    ttl-minutes: 60